# Server (Render ke liye important)
server.port=${PORT:8080}

# MongoDB (Render se env variable lega)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:entangle}

# Optional (good practice)
spring.application.name=entangle-backend

# Logging (debug ke liye useful)
logging.level.org.springframework=INFO